- name: Download and execute the NodeSource setup script for Node.js 18.x
  shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present
