#!/bin/sh
instance_name=$1

printf "deployment $instance_name\n"


multipass launch --name $instance_name
mkdir -p ~/devops/ansible-deploy-test/ssh/$instance_name
ssh-keygen -C $instance_name -f ~/devops/ansible-deploy-test/ssh/$instance_name/id_rsa -N ""

cat ~/devops/ansible-deploy-test/ssh/$instance_name/id_rsa.pub | multipass exec $instance_name -- sudo tee -a /home/ubuntu/.ssh/authorized_keys

multipass exec $instance_name -- sudo chmod 600 /home/ubuntu/.ssh/authorized_keys
multipass exec $instance_name -- sudo chmod 700 /home/ubuntu/.ssh


